//
//  CountryConstants.swift
//  Fastgo
//
//  Created by vishwas on 12/26/25.
//

struct CountryConstant {
    
   static let countries: [Country] = [
        Country(name: "Afghanistan", code: "AF", dialCode: "+93"),
        Country(name: "Albania", code: "AL", dialCode: "+355"),
        Country(name: "Algeria", code: "DZ", dialCode: "+213"),
        Country(name: "Andorra", code: "AD", dialCode: "+376"),
        Country(name: "Angola", code: "AO", dialCode: "+244"),
        Country(name: "Antigua and Barbuda", code: "AG", dialCode: "+1-268"),
        Country(name: "Argentina", code: "AR", dialCode: "+54"),
        Country(name: "Armenia", code: "AM", dialCode: "+374"),
        Country(name: "Australia", code: "AU", dialCode: "+61"),
        Country(name: "Austria", code: "AT", dialCode: "+43"),
        Country(name: "Azerbaijan", code: "AZ", dialCode: "+994"),
        Country(name: "Bahamas", code: "BS", dialCode: "+1-242"),
        Country(name: "Bahrain", code: "BH", dialCode: "+973"),
        Country(name: "Bangladesh", code: "BD", dialCode: "+880"),
        Country(name: "Barbados", code: "BB", dialCode: "+1-246"),
        Country(name: "Belarus", code: "BY", dialCode: "+375"),
        Country(name: "Belgium", code: "BE", dialCode: "+32"),
        Country(name: "Belize", code: "BZ", dialCode: "+501"),
        Country(name: "Benin", code: "BJ", dialCode: "+229"),
        Country(name: "Bhutan", code: "BT", dialCode: "+975"),
        Country(name: "Bolivia", code: "BO", dialCode: "+591"),
        Country(name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387"),
        Country(name: "Botswana", code: "BW", dialCode: "+267"),
        Country(name: "Brazil", code: "BR", dialCode: "+55"),
        Country(name: "Brunei", code: "BN", dialCode: "+673"),
        Country(name: "Bulgaria", code: "BG", dialCode: "+359"),
        Country(name: "Burkina Faso", code: "BF", dialCode: "+226"),
        Country(name: "Burundi", code: "BI", dialCode: "+257"),
        Country(name: "Cabo Verde", code: "CV", dialCode: "+238"),
        Country(name: "Cambodia", code: "KH", dialCode: "+855"),
        Country(name: "Cameroon", code: "CM", dialCode: "+237"),
        Country(name: "Canada", code: "CA", dialCode: "+1"),
        Country(name: "Central African Republic", code: "CF", dialCode: "+236"),
        Country(name: "Chad", code: "TD", dialCode: "+235"),
        Country(name: "Chile", code: "CL", dialCode: "+56"),
        Country(name: "China", code: "CN", dialCode: "+86"),
        Country(name: "Colombia", code: "CO", dialCode: "+57"),
        Country(name: "Comoros", code: "KM", dialCode: "+269"),
        Country(name: "Congo", code: "CD", dialCode: "+243"),
        Country(name: "Costa Rica", code: "CR", dialCode: "+506"),
        Country(name: "Côte d'Ivoire", code: "CI", dialCode: "+225"),
        Country(name: "Croatia", code: "HR", dialCode: "+385"),
        Country(name: "Cuba", code: "CU", dialCode: "+53"),
        Country(name: "Cyprus", code: "CY", dialCode: "+357"),
        Country(name: "Czechia", code: "CZ", dialCode: "+420"),
        Country(name: "Denmark", code: "DK", dialCode: "+45"),
        Country(name: "Djibouti", code: "DJ", dialCode: "+253"),
        Country(name: "Dominica", code: "DM", dialCode: "+1-767"),
        Country(name: "Dominican Republic", code: "DO", dialCode: "+1-809"),
        Country(name: "Ecuador", code: "EC", dialCode: "+593"),
        Country(name: "Egypt", code: "EG", dialCode: "+20"),
        Country(name: "El Salvador", code: "SV", dialCode: "+503"),
        Country(name: "Equatorial Guinea", code: "GQ", dialCode: "+240"),
        Country(name: "Eritrea", code: "ER", dialCode: "+291"),
        Country(name: "Estonia", code: "EE", dialCode: "+372"),
        Country(name: "Eswatini", code: "SZ", dialCode: "+268"),
        Country(name: "Ethiopia", code: "ET", dialCode: "+251"),
        Country(name: "Faroe Islands", code: "FO", dialCode: "+298"),
        Country(name: "Fiji", code: "FJ", dialCode: "+679"),
        Country(name: "Finland", code: "FI", dialCode: "+358"),
        Country(name: "France", code: "FR", dialCode: "+33"),
        Country(name: "Gabon", code: "GA", dialCode: "+241"),
        Country(name: "Gambia", code: "GM", dialCode: "+220"),
        Country(name: "Georgia", code: "GE", dialCode: "+995"),
        Country(name: "Germany", code: "DE", dialCode: "+49"),
        Country(name: "Ghana", code: "GH", dialCode: "+233"),
        Country(name: "Greece", code: "GR", dialCode: "+30"),
        Country(name: "Greenland", code: "GL", dialCode: "+299"),
        Country(name: "Grenada", code: "GD", dialCode: "+1-473"),
        Country(name: "Guatemala", code: "GT", dialCode: "+502"),
        Country(name: "Guinea", code: "GN", dialCode: "+224"),
        Country(name: "Guinea-Bissau", code: "GW", dialCode: "+245"),
        Country(name: "Guyana", code: "GY", dialCode: "+592"),
        Country(name: "Haiti", code: "HT", dialCode: "+509"),
        Country(name: "Honduras", code: "HN", dialCode: "+504"),
        Country(name: "Hungary", code: "HU", dialCode: "+36"),
        Country(name: "Iceland", code: "IS", dialCode: "+354"),
        Country(name: "India", code: "IN", dialCode: "+91"),
        Country(name: "Indonesia", code: "ID", dialCode: "+62"),
        Country(name: "Iran", code: "IR", dialCode: "+98"),
        Country(name: "Iraq", code: "IQ", dialCode: "+964"),
        Country(name: "Ireland", code: "IE", dialCode: "+353"),
        Country(name: "Israel", code: "IL", dialCode: "+972"),
        Country(name: "Italy", code: "IT", dialCode: "+39"),
        Country(name: "Jamaica", code: "JM", dialCode: "+1-876"),
        Country(name: "Japan", code: "JP", dialCode: "+81"),
        Country(name: "Jordan", code: "JO", dialCode: "+962"),
        Country(name: "Kazakhstan", code: "KZ", dialCode: "+7"),
        Country(name: "Kenya", code: "KE", dialCode: "+254"),
        Country(name: "Kiribati", code: "KI", dialCode: "+686"),
        Country(name: "Kosovo", code: "XK", dialCode: "+383"),
        Country(name: "Kuwait", code: "KW", dialCode: "+965"),
        Country(name: "Kyrgyzstan", code: "KG", dialCode: "+996"),
        Country(name: "Laos", code: "LA", dialCode: "+856"),
        Country(name: "Latvia", code: "LV", dialCode: "+371"),
        Country(name: "Lebanon", code: "LB", dialCode: "+961"),
        Country(name: "Lesotho", code: "LS", dialCode: "+266"),
        Country(name: "Liberia", code: "LR", dialCode: "+231"),
        Country(name: "Libya", code: "LY", dialCode: "+218"),
        Country(name: "Liechtenstein", code: "LI", dialCode: "+423"),
        Country(name: "Lithuania", code: "LT", dialCode: "+370"),
        Country(name: "Luxembourg", code: "LU", dialCode: "+352"),
    ].sorted { $0.name < $1.name }
    
}
